name: Push

on:
  push:
    branches: [ master ]
    tags:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make local

    - name: Test
      run: make test
    
    - name: Get Tag
      id: get_tag
      run: |
        echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Get highest release
      id: get_highest_release
      run: |
        echo ::set-output name=HIGHEST::$(./hack/get-highest-release.sh)

    - name: Set TAG_LATEST
      id: set_tag_latest
      if: ${{ steps.get_highest_release }} == $${{ steps.get_tag.outputs.TAG }}
      run: |
        echo ::set-output name=TAG_LATEST::$(echo true)

    - name: Publish container image
      run: |
        #docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        TAG=${{ steps.get_tag.outputs.TAG }} TAG_LATEST=${{ steps.set_tag_latest.TAG_LATEST }} make push
